server:
  port: 8083
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  data:
    mongodb:
      host: anilspersonalpagescosmosdb.mongo.cosmos.azure.com
      uri: mongodb://anilspersonalpagescosmosdb:GrvOA8AewXAeawOtaUZfIR9oCeiFqpOwcMdBJ8N7SO1u79ftDZFGHouMtRjgH0nX2cKRmcaxW8p5ACDb8tCBsw==@anilspersonalpagescosmosdb.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@anilspersonalpagescosmosdb@
      database: mydb
  cloud:
     azure:
       eventhubs:
         connection-string: Endpoint=sb://anilstraining.servicebus.windows.net/;SharedAccessKeyName=anilsEventhubAccessKey;SharedAccessKey=BEPJ7vsrvQ9v6xh2zSTTppqoa2AhXJPYZACmBzr/kqA=;EntityPath=newseventshub
     stream:
       bindings:
         newsRegistered-out-0:
           destination: newseventshub
       function:
         definition: supply;
       poller:
         initial-delay: 0
         fixed-delay: 1000